runners:
  - name: gpu-runner
    cloud: aws
    gpu: nvidia-tesla-t4
    instance_type: t3.nano
    machine_image: ami-0229f8cfc24033d05
    preemptible: true
    workflow: .github/workflows/test.yml
